### ISSUE TITLE
Some files in /media/mmcblk0p1 are not belong to any package

### ISSUE THREAD

**Issue by herry13** [fruit-testbed/apks#5]
There's no way to update some files in `/media/mmcblk0p1` through Alpine Package Management since they are not belong to any package.

```shell
# for f in $(ls /media/mmcblk0p1); do apk info -W /media/mmcblk0p1/$f; done
/media/mmcblk0p1/LICENCE.broadcom is owned by fruit-rpi-bootloader-1.20180417-r0
ERROR: /media/mmcblk0p1/bcm2708-rpi-0-w.dtb: Could not find owner package
ERROR: /media/mmcblk0p1/bcm2708-rpi-b-plus.dtb: Could not find owner package
ERROR: /media/mmcblk0p1/bcm2708-rpi-b.dtb: Could not find owner package
ERROR: /media/mmcblk0p1/bcm2708-rpi-cm.dtb: Could not find owner package
ERROR: /media/mmcblk0p1/bcm2709-rpi-2-b.dtb: Could not find owner package
ERROR: /media/mmcblk0p1/bcm2710-rpi-3-b-plus.dtb: Could not find owner package
ERROR: /media/mmcblk0p1/bcm2710-rpi-3-b.dtb: Could not find owner package
ERROR: /media/mmcblk0p1/bcm2710-rpi-cm3.dtb: Could not find owner package
ERROR: /media/mmcblk0p1/bcm2835-rpi-a-plus.dtb: Could not find owner package
ERROR: /media/mmcblk0p1/bcm2835-rpi-a.dtb: Could not find owner package
ERROR: /media/mmcblk0p1/bcm2835-rpi-b-plus.dtb: Could not find owner package
ERROR: /media/mmcblk0p1/bcm2835-rpi-b-rev2.dtb: Could not find owner package
ERROR: /media/mmcblk0p1/bcm2835-rpi-b.dtb: Could not find owner package
ERROR: /media/mmcblk0p1/bcm2835-rpi-zero-w.dtb: Could not find owner package
ERROR: /media/mmcblk0p1/bcm2835-rpi-zero.dtb: Could not find owner package
ERROR: /media/mmcblk0p1/bcm2836-rpi-2-b.dtb: Could not find owner package
ERROR: /media/mmcblk0p1/bcm2837-rpi-3-b.dtb: Could not find owner package
ERROR: /media/mmcblk0p1/boot-root.env: Could not find owner package
/media/mmcblk0p1/boot.scr is owned by fruit-u-boot-2018.07-r0
/media/mmcblk0p1/bootcode.bin is owned by fruit-rpi-bootloader-1.20180417-r0
/media/mmcblk0p1/config.txt is owned by fruit-u-boot-2018.07-r0
/media/mmcblk0p1/fixup.dat is owned by fruit-rpi-bootloader-1.20180417-r0
ERROR: /media/mmcblk0p1/fruit.json: Could not find owner package
ERROR: /media/mmcblk0p1/overlays: Could not find owner package
/media/mmcblk0p1/start.elf is owned by fruit-rpi-bootloader-1.20180417-r0
/media/mmcblk0p1/u-boot-rpi.bin is owned by fruit-u-boot-2018.07-r0
/media/mmcblk0p1/u-boot-rpi2.bin is owned by fruit-u-boot-2018.07-r0
/media/mmcblk0p1/u-boot-rpi3.bin is owned by fruit-u-boot-2018.07-r0
```

**TODO**
- [x] `/media/mmcblk0p1/boot-root.env` and `/media/mmcblk0p1/fruit.json` should be kept as it is since they are configuration files created by the user or management-script.
- [x] `/media/mmcblk0p1/bcm*` and `/media/mmcblk0p1/overlays` should belong to package `rpi-devicetree` -- fixed in 0b1872d2b17212e39648d1f01d92d11379de0330
- [x] `fruit-update` should mount `/media/mmcblk0p1` to `/media/root-bak/media/mmcblk0p1` before invoking `apk update` -- fixed in https://github.com/fruit-testbed/fruit-agent/commit/357789673f7808fe7e8673a21a63e3a323eaa8c5
